vms:
  - type: windows
    name: "windowsvm1"

    cpu: 2   
    memory: 4096MB

    network:
      ip: 192.168.1.1
      netmask: 255.255.255.0
      gateway: 192.168.1.254
      dns: 8.8.8.8
      
    network_switch: 'Nested NAT Switch' 

    src_vhd: "D:\\VHDs\\GoldenImages\\win2022-gold.vhdx"
    dest_vhd: "D:\\Hyper-V\\Virtual hard disks\\windowsvm1.vhdx"

